
- name: Create Cron Job for Web Server configuration
  hosts: localhost
  connection: local
  tasks:
  - name: Cron Job web server configuration
    cron:
     name: "httpd yml configuration"
     minute: "*"
     hour: "*"
     job: 'ansible-playbook -i ~/ansible/contrib/inventory/azure_rm.py ~/PartsUnlimitedMRP/Labfiles/AZ-400T05-ImplemntgAppInfra/Labfiles/ansible/httpd.yml --extra-vars  "vmname=vmw$